### ISSUE TITLE
Автосопоставление

### ISSUE THREAD

**Issue by Akior** [LinFor/jellyfin-plugin-kinopoisk#1]
Как правильно именовать файл для автосопоставления по КП ?

Сейчас у меня все файлы вида "ИМЯ [ENG NAME] (год) [resolution] [codec] [lang] (kinopoisk-id)
например:
Кровь машин [Blood Machines] (2019) [1080p] [x264] [2ru, en] (kp-1178053)

Возможно ли научить плагин автосопоставлять такий файлы ?

**Comment by LinFor** [comment]
Интересный вопрос. Сам этот плагин имя файла не разбирает, jellyfin передаёт сразу разобранный своего рода [запрос на поиск](https://github.com/jellyfin/jellyfin/blob/a96c0a72b8574c563a91c7d5cf8aaf2541efe201/MediaBrowser.Controller/Providers/ItemLookupInfo.cs). Т.е. уже готовые поля Name, Year и т.д.
Ровно тот же набор полей ты видишь, когда нажимаешь кнопку "Распознать".

Разбором занимается сам jellyfin и почему-то кодом предусмотрено, что из всего имени его интересуют [только Name и Year](https://github.com/jellyfin/jellyfin/blob/44dbee6ef26cb5b3bb641a0d671197321e97a8ac/Emby.Server.Implementations/Library/LibraryManager.cs#L2637).

В общем, беглым просмотром ответ получается "нет", но пожалуй надо ещё внимательней процесс изучить.

**Comment by Akior** [comment]
Получилось внимательней изучить процесс?
Ответ так же "нет" ?

**Comment by shemanaev** [comment]
Jellyfin поддерживает id [формата `[id=xxx]`](https://github.com/jellyfin/jellyfin/blob/aff65adca93ef82d6c5d7765d18a69f7fd164f7c/Emby.Server.Implementations/Library/PathExtensions.cs#L20-L49), но почему-то пробрасывают они только [`tmdbid`, `imdbid`](https://github.com/jellyfin/jellyfin/blob/ad5c41b5429d245dd3353423ed47b695eba3858d/Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs#L339-L368) и [`tvdbid`](https://github.com/jellyfin/jellyfin/blob/100e9d586dff877610c488936aa035f61f6fedb5/Emby.Server.Implementations/Library/Resolvers/TV/SeriesResolver.cs#L212-L222).

Ответ — «нет».
Пути решения: API Кинопоиска, которое умеет искать по IMDB Id или предложить изменение в логике обработки аттрибутов Jellyfin'ом, чтобы можно было забирать `[kinopoiskid=XXXX]` из имени.

**Comment by Akior** [comment]
Реализовать ttimdb в плагине кинопоиска возможно ?

**Comment by svyaznoy362** [comment]
Привет, возможно адаптировать плагин для emby ?

**Comment by LinFor** [comment]
@Akior я там версию 10.7.5.0 положил... Потестируй, пожалуйста, должно автоматом привязывать по шаблонам в имени файла/папки kp-12345 и kp12345. Подхватывать должно по "Сканировать медиатеку" и по "Обновить медиаданные" (ну и просто при появлении нового файла/каталога сериала), при "Распознать" имя файла игнорируется.

@svyaznoy362 наверное да, но я не возьмусь, я её даже в глаза не видел.

**Comment by svyaznoy362** [comment]
> @Akior я там версию 10.7.5.0 положил... Потестируй, пожалуйста, должно автоматом привязывать по шаблонам в имени файла/папки kp-12345 и kp12345. Подхватывать должно по "Сканировать медиатеку" и по "Обновить медиаданные" (ну и просто при появлении нового файла/каталога сериала), при "Распознать" имя файла игнорируется.
> 
> @svyaznoy362 наверное да, но я не возьмусь, я её даже в глаза не видел.

А можно привязать хотя бы отзывы к данному плагину, как это сделано в plex

**Comment by LinFor** [comment]
> А можно привязать хотя бы отзывы к данному плагину, как это сделано в plex

А есть какой-то примерчик, где в jellyfin показываются отзывы? Не уверен, что оно такое вообще умеет...

**Comment by Akior** [comment]
> @Akior я там версию 10.7.5.0 положил... Потестируй, пожалуйста, должно автоматом привязывать по шаблонам в имени файла/папки kp-12345 и kp12345. Подхватывать должно по "Сканировать медиатеку" и по "Обновить медиаданные" (ну и просто при появлении нового файла/каталога сериала), при "Распознать" имя файла игнорируется.
> 
> @svyaznoy362 наверное да, но я не возьмусь, я её даже в глаза не видел.

Просто волшебно! 100% совпадения
![image](https://user-images.githubusercontent.com/5903863/119400027-461f0180-bce2-11eb-9cef-062921693783.png)
