### ISSUE TITLE
URL in Description

### ISSUE THREAD

**Issue by urtaevS** [LinFor/jellyfin-plugin-kinopoisk#16]
Пожалуйста, добавьте ссылку на фильм в Кинопоиск к описанию фильма.
![Снимок экрана 2024-04-28 в 16 53 39](https://github.com/LinFor/jellyfin-plugin-kinopoisk/assets/66906118/3f26f1e9-3d04-4d4e-8106-c4ae00d9bc29)

**Comment by skrashevich** [comment]
Ссылка будет, если в метаданных фильма/сериала/эпизода заполнено поле КинопоискID

![image](https://github.com/LinFor/jellyfin-plugin-kinopoisk/assets/15078499/b89cb752-542b-4d2d-9574-b85481489593)

**Comment by urtaevS** [comment]
Спасибо за объяснение.
Это поле надо вручную заполнять?
