### ISSUE TITLE
Doesn't support by jellyfin 10.9.0

### ISSUE THREAD

**Issue by ydrob** [LinFor/jellyfin-plugin-kinopoisk#17]
New version of jellyfin doesn't support the plugin
![Screenshot_1](https://github.com/LinFor/jellyfin-plugin-kinopoisk/assets/77321248/a3c8ebf9-1d7b-4022-ba3f-1524bef651d3)
![image](https://github.com/LinFor/jellyfin-plugin-kinopoisk/assets/77321248/2f1221fb-7756-4d1c-83e6-9b46928b9ffc)

**Comment by skrashevich** [comment]
Work in Progress
https://github.com/LinFor/jellyfin-plugin-kinopoisk/tree/v10-9 (currently under development)

**Comment by skrashevich** [comment]
To solve this problem can try to install beta-version from my repo: `https://raw.githubusercontent.com/skrashevich/jellyfin-plugin-kinopoisk/master/dist/manifest.json` (remove current plug-in. remove current repo from sources.yaml. 
No guarantees, but personally, I got one installed.

**Comment by ydrob** [comment]
Yes, now it works, thanks, are you going to put this version to main branch?

**Comment by skrashevich** [comment]
> Yes, now it works, thanks, are you going to put this version to main branch?

Done
